modLoader="javafml"
loaderVersion="[${fml_min},)"
license="${license}"

[[mods]]
modId="${modid}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="examplemod.png"
authors="Azmalent"
description='''
Adds effect descriptions to potion tooltips.
'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="CLIENT"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version}]"
    ordering="NONE"
    side="CLIENT"


[[dependencies.examplemod]]
    modId="botania"
    mandatory=false
    ordering="BEFORE"
    side="CLIENT"